name: CICD

#Trigers
on:
  push:
    branches:
      - main    # solo cuando se haga un push en main se va a ejecutar el workflow
    tags:
      - 'v*'    # también se ejecutará el workflow cuando se haga un push con una etiqueta que comience con "v"
  pull_request:

# Jobs
jobs:
  # Linterna: chequea el codigo con ruff
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Set up python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run linter
      run: ruff check .  


  test:
  # Este job depende del job de lint, es decir, se ejecutará solo si el job de lint se ejecuta correctamente
  # tests: ejecuta los tests con pytest
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        python-version: ["3.10", "3.13"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Set up python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest tests/


  docker-build:
  # construye la imagen de docker, este job depende del job de test, es decir, se ejecutará solo si el job de test se ejecuta correctamente
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Build docker image
      run: docker build -t github-actions-workshop:latest .

  docker-push:
  # este job se ejecutará solo si el job de docker-build se ejecuta correctamente
    runs-on: ubuntu-latest
    needs: docker-build

    if: github.event_name == 'push'

    permissions:
      contents: read    # es importante para no borrar nada, solo para leer el repositorio

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Login in Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Extract Docker metadata
      id: metadata
      uses: docker/metadata-action@v5
      with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-workshop
          tags: |
            type:raw, value=latest
            type:raw, value=main, enable={{is_default_branch}}
            type:ref, event=tag
            type:sha
    - name: Print generated tags
      run: echo "Generated tags  ${{ steps.metadata.outputs.tags }}"
    - name: Build & push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: docker-push
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Trigger render PROD deploy
        run: curl -X POST "${{ secrets.RENDER_PROD_DEPLOY_HOOK}}" 
